version: "3.9"

name: ${PROJECT_NAME}

services:
  mqtt_client:
    build: ./services/mqtt_client
    container_name: kap_mqtt_client
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      kap_net:
        ipv4_address: 172.16.19.15

networks:
  kap_net:
    name: kap-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.19.0/24